defaults:
  - cutouts: cutouts
  - _self_

hydra:
  run:
    dir: ${general.projectdir}
  output_subdir: ${general.projectdir}

# ================= General Settings and Paths ================= #

general:
  task: ???
  project_name: ???
  workdir: ${hydra:runtime.cwd}
  projectdir: ${general.workdir}/data/projects/${general.project_name}
  resultsdir: ${general.projectdir}/results
  cpu_denominator: 4

blob_names:
  developed: semifield-developed-images
  synth: semifield-synth
  cutout: semifield-cutouts

# =================== Data Paths and Settings ================== #

data:
  datadir: ${general.workdir}/data
  developed: ${data.datadir}/${blob_names.developed}
  srcbatchdir: /mnt/research-projects/s/screberg/longterm_images/semifield-developed-images
  cutoutdir: /mnt/research-projects/s/screberg/longterm_images/semifield-cutouts
  csvpath: ${general.projectdir}/${general.project_name}.csv
  common_name_distribution: ${general.projectdir}/common_name_distribution.csv
  batch_distribution: ${general.projectdir}/batch_distribution.csv
  images: ${general.resultsdir}/images
  semantic_masks: ${general.resultsdir}/meta_masks/semantic_masks
  metadata: ${general.resultsdir}/metadata
  cropped_images: ${general.resultsdir}/cropped_images
  cropped_masks: ${general.resultsdir}/cropped_masks
  remapped_masks: ${general.resultsdir}/remapped_masks
  datacsv: ${general.projectdir}/${general.project_name}.csv

# ==================== Image Processing ======================== #

mask2yolo:
  cutouts_or_imgs: cutouts
  testing:
    test: False
    sample: 10
    write_samples: True

crop_split:
  M: 640
  N: 640
  exclude_empty_tiles: True

# ================== Classes and Metadata ====================== #

classes:
  present_class_info: ${general.resultsdir}/present_classes.csv
  all_class_info: ${general.resultsdir}/all_classes.csv
  true_mask_palette: ${general.resultsdir}/true_mask_palette.csv
  common_name_file: ${general.resultsdir}/common_names.csv
  USDA_symbols_file: ${general.resultsdir}/USDA_symbols.csv
  speciesinfo_json: /home/psa_images/SemiF-AnnotationPipeline/data/semifield-utils/species_information/species_info.json
  coco_categories: ${general.projectdir}/coco_categories.json

# ==================== Data Splitting ========================== #

data_split:
  testsize: .01
  random_state: 42
  imgs2split: ${data.cropped_images}
  masks2split: ${data.cropped_masks}
  splitsdir: ${general.resultsdir}/splits

# =========================== YOLO ============================= #

yolo:
  use_splits: True

# ===================== Data Combination ======================= #

combine_data:
  - cereal_rye
  - crimson_clover
  - hairy_vetch
  - mustards
  - radish
  - triticale
  - winter_pea
  - winter_wheat
  - oats
  - barley
  - black_oats
